mkdir module
mkdir module/StickyNotes
mkdir module/StickyNotes/config
mkdir module/StickyNotes/src 
mkdir module/StickyNotes/src/StickyNotes
mkdir module/StickyNotes/src/StickyNotes/Controller 
mkdir module/StickyNotes/src/StickyNotes/Form 
mkdir module/StickyNotes/src/StickyNotes/Model 
mkdir module/StickyNotes/view
mkdir module/StickyNotes/view/sticky-notes 
mkdir module/StickyNotes/view/sticky-notes/sticky-notes